all:
  vars:
    ansible_user: osboxes
    ansible_python_interpreter: /usr/bin/python3
    domain: asr.es
    internal_network: 192.168.0.0/24
    dns_servers: [192.168.0.102, 192.168.0.103]
    dns_forwarders: [150.128.98.10, 8.8.8.8]
    dns_phase: bootstrap   # cambia a 'final' tras desplegar BIND9
  children:
    gateway:
      hosts:
        vbox-gateway:
          ansible_host: 192.168.0.1
          ip_int: 192.168.0.1
          ip_ext: 150.128.63.10   # CAMBIAR a la IP del laboratorio
          iface_int: enp0s8
          iface_ext: enp0s3
          ext_gw: 150.128.48.1
          ext_prefix: 20
    web:
      hosts:
        vbox1:
          ansible_host: 192.168.0.100
          ip: 192.168.0.100
          iface: enp0s3
    ftp:
      hosts:
        vbox2:
          ansible_host: 192.168.0.101
          ip: 192.168.0.101
          iface: enp0s3
    dns_master:
      hosts:
        vbox-DNS:
          ansible_host: 192.168.0.102
          ip: 192.168.0.102
          iface: enp0s3
    dns_slave:
      hosts:
        vbox-DNS2:
          ansible_host: 192.168.0.103
          ip: 192.168.0.103
          iface: enp0s3
    samba_server:
      hosts:
        vbox2:
    samba_clients:
      hosts:
        vbox-gateway:
        vbox1:
        vbox-DNS:
        vbox-DNS2:
    monitor_master:
      hosts:
        vbox-gateway:
    monitor_agents:
      hosts:
        vbox1:
        vbox2:
        vbox-DNS:
        vbox-DNS2:
    nagios_clients:
      hosts:
        vbox-gateway:
        vbox1:
        vbox2:
        vbox-DNS:
        vbox-DNS2:
    nagios_server:
      hosts:
        vbox-nagios:
          ansible_host: 192.168.0.150
          ip: 192.168.0.150
          iface: enp0s3
