---
- name: Instalar apache2
  ansible.builtin.apt:
    name: apache2
    state: present
    update_cache: true

- name: Index sencillo
  ansible.builtin.copy:
    dest: /var/www/html/index.html
    content: "<h1>vbox1 - WEB ASR</h1>\n"
    mode: '0644'

- name: Servicio activo
  ansible.builtin.service:
    name: apache2
    enabled: true
    state: started
